### ISSUE TITLE
Timing information is off

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#138]
Issue: The same timing is mentioned for the entire lab as for Task 1 in the lab. This applies to many labs. Example from Lab 1:

![image](https://user-images.githubusercontent.com/1765732/123572468-24051d00-d781-11eb-9e83-1ebc6d60440e.png)

**Comment by Randall-Knapp** [comment]
@VitalyMCT Thanks
