### ISSUE TITLE
Lab 5 - UI Change

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#141]
Azure UI changed around the following two options, so the instructions need to be updated:

Removed/moved:

- Account kind | StorageV2 (general purpose v2)

Renamed to "Redundancy"

- Replication | Locally redundant storage (LRS)

Renamed to "Data Storage"

- Click the name of the new storage account, scroll to the Blob service section in the left menu, and then click Containers.

**Comment by Randall-Knapp** [comment]
@VitalyMCT Nice work, and thanks for the heads up.
