### ISSUE TITLE
Module 00 - Course Introduction - Readme link is blank

### ISSUE THREAD

**Issue by DaConfusedSoul** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#150]
# Module: 00
#### Step: 00

Description of issue

Clicking on the readme opens up a blank page.

Repro steps:

1. Go to page: https://github.com/MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals
2. Scroll down to readme.md
3. Click on Link to Walkthroughs (HTML format)
4. Click on the Walkthrough link of module 00 (see highlighted in yellow)
5. A blank page opens up.

![image](https://user-images.githubusercontent.com/72460524/126746224-06f7db32-e6fc-4f6b-acca-ff5ef56f8847.png)

![image](https://user-images.githubusercontent.com/72460524/126746306-6de011dc-4a76-4eb1-838f-4208358b97b8.png)

**Comment by Randall-Knapp** [comment]
It is an error log. Right now, we have no errors.
