### ISSUE TITLE
Mod 3 - Image file in docker hub doesn't work as shown

### ISSUE THREAD

**Issue by CJ1S** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#159]
In the creation of the container it states to use:
Image source: Docker Hub or other registry
Image type: public
Image: microsoft/aci-helloworld
OS type: linux

This fails every time with "BadRequest" 

Replacing the Image works fine as: mcr.microsoft.com/azuredocs/aci-helloworld

**Comment by Randall-Knapp** [comment]
This has been fixed.
