### ISSUE TITLE
Wrong Container Image for 02/03 Labs

### ISSUE THREAD

**Issue by haimdagan8** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#160]
# Module: 02
###### Value: microsoft/aci-helloworld -> **mcr.microsoft.com/azuredocs/aci-helloworld**

# Module: 02
###### Value: microsoft/aci-helloworld -> **mcr.microsoft.com/azuredocs/aci-helloworld**

**Comment by wentingd** [comment]
Am really expecting this would get some attention soon....

**Comment by Randall-Knapp** [comment]
This has been fixed.
