### ISSUE TITLE
Lab 17, missing permissions over selected scope

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#194]
# Module: 03
#### Step: 6

Description of issue

Signed in as administrator. i get the following issue:

*upon creating the policy, I get the following error message: "you cannot perform this action without the following permissions over selected scope: (Microsoft.Authorization/PolicyAssignments/write).

I have tried to sign out and back into the account. tried waiting 15 minutes for all permissions to be assigned, but no luck so far.
Very grateful for thoughts and suggestions. thank you.

![image](https://user-images.githubusercontent.com/89986870/174448454-d067c1d0-6fde-4668-b59e-b0af63f0fe0a.png)

**Comment by Yiizo** [comment]
Hi Chasst, It looks like you have not selected the Resource Group. Please ensure you are selecting a resource group to be able to assign the Policy Successfully.

**Comment by chaast** [comment]
Ah thank you..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chaast** [comment]
the feedback about selected the Resources Group worked-- thank you very much for your feedback Yiizo...

it's missing from step 5 instructions in this lab - when selecting the scope...
