### ISSUE TITLE
01-VM is sluggish

### ISSUE THREAD

**Issue by staleycyn** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#21]
# Module: 02
#### Step: 00

Location: 01 - Create a virtual machine in the portal | Module 02 - Core Azure Services
Issue/Request: The Azure-based Windows VM is very very sluggish, to the point of being nearly unusable. The recommended size in the lab instructions could be bumped up a bit.

**Comment by polichtm** [comment]
addressed
