### ISSUE TITLE
Downloadable files missing Walk-through 11

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#26]
Download of the provided Word Zip file is missing 11!

**Comment by itbland** [comment]
To clarify:
If you click **Download Latest Walkthroughs (Word format)** in the **readme.md**, (A *REALLY* nice feature, Thanks!) the 12/10 release is missing Walkthrough 11.

**Comment by itbland** [comment]
Oops, didn't mean to close.

**Comment by staleycyn** [comment]
Now that we have the HTML pages, the release file will be removed. To create the missing file simply copy the HTML to Word. It does a nice job of keeping the formatting.

**Comment by polichtm** [comment]
considered closed
