### ISSUE TITLE
Suggestion: Change password to "new standard"

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#29]
# Module: All
#### Step: 00

In most other MOC/ILT courses the password used is Pa55w.rd1234. Would it be possible to change the passwords used in the walkthroughs to this? It would make the life a lot easier for MCTs ;-)

**Comment by polichtm** [comment]
Could you clarify why using a particular password in the walkthroughs of this course would make the life of MCTs a lot easier?
rgds
Marcin

**Comment by TommyKobber** [comment]
Because typing the wrong password in front of students because the password is different from last weeks course is waste of valuable time and annoying to both me and the students. And yes, I could just choose my own password instead of the suggested, but sometimes it's faster to use copy/paste in the process. But if I'm the only one having this issue then just leave it. I'll live with it

**Comment by staleycyn** [comment]
We have not had this comment from any other MCTs. There is no content specification around what username and password should be used in our classes. We will keep an eye on this, but close the issure for new.

**Comment by polichtm** [comment]
Closing the issue
