### ISSUE TITLE
Walkthrough 17 policy definition: "Require specified tag" or "Require a tag on resources"

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#31]
# Module: 03
#### Step: 05

Description of issue:
Did the policy definition **Require specified tag** change to **Require a tag on resources**?  

Repro steps:
If yes, can we update Walkthrough 17 - Implement resource tagging, Task 1, Step 5 from **Require specified tag** to **Require a tag on resources**?  

![policy](https://user-images.githubusercontent.com/11367710/76348712-0dfaf100-62df-11ea-8b19-8fa2eff0e2e7.PNG)

**Comment by markturpinMSFT** [comment]
Further detail on new tag policy.

Task 1 description - Replace "Require specified tag" with "Require a tag on resources"

- Step 5 - Replace "Require specified tag" with "Require a tag on resources" and update screenshot with new policy definition

- Step 7 - Replace "Require specified tag" with "Require a tag on resources" and update screenshot with new policy definition

Task 2 - Need to replace the error screenshot if the Policy name has changed to "Require a tag on resources"

Task 4 - Replace "Require specific tag" with "Require a tag on resources" in task description and step 2

**Comment by polichtm** [comment]
updated
