### ISSUE TITLE
Walkthrough 05 - Create a SQL database, Task 1 Step 4 - Access Checkbox moved 

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#33]
# Module: 02
#### Step: 04

Description of issue

Walkthrough  05 - Create a SQL database, Task 1 Step 4:  The **Allow Azure services to access server** checkbox has been moved to the Networking tab, renamed **Allow Azure services and resources to access this server**, and should be set to Yes instead of checked.  
1.  Remove:  Allow Azure services to access server Check the box and crop New Server image to remove checkbox at bottom
2. Add a step prior to Step 5:  Move to the **Networking** tab. Setting:  Allow Azure services and resources to access this server and Value:  Yes.  Add new image as shown below.

![foundhere](https://user-images.githubusercontent.com/11367710/76441727-44477780-6396-11ea-9b2c-83c40cf19b61.PNG)

**Comment by polichtm** [comment]
updated
