### ISSUE TITLE
alkthrough 11 - Create a VM with the CLI, Task 2, Step 6:  \ vs ^

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#34]
# Module: 02
#### Step: 06

Description of issue

Walkthrough 11 - Create a VM with the CLI, Task 2, Step 6 works on Linux/Mac but in Windows command prompt you may find that you need to replace the line continuation character backslash (\) with a caret (^).  

A simple note regarding the difference may suffice, two code tabs - one for Windows and one for Linux may be used, and other solutions will work but I am in favor of students seeing that they can run CLI in the command prompt.

**Comment by polichtm** [comment]
updated
