### ISSUE TITLE
Walkthrough 21 - Open a Support Request; Task 1, Step 4 screenshot and instructions need updating.

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#35]
# Module: 04
#### Step: 04

Description of issue
Walkthrough 21 - Open a Support Request; Task 1, Step 4 screenshot and instructions need updating.  

1. Remove:  Resource   General question
2. Break setting into two:   Problem type   VM performance, Disk throughput is lower than expected
    Problem type   VM performance
    Problem subtype   Disk throughput is lower than expected
 3. Update screenshot as attached.
![support](https://user-images.githubusercontent.com/11367710/76642897-0d9e6800-6522-11ea-8bbe-b9dfc1f630ab.png)

**Comment by polichtm** [comment]
updated (there is no screenshot in the current instructions)
