### ISSUE TITLE
Walkthrough 21 - Open a Support Request; Task 2, Step 1 screenshot and instructions need updating.  

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#36]
# Module: 04
#### Step: 01

Walkthrough 21 - Open a Support Request; Task 2, Step 1 screenshot and instructions need updating.  
1. Break setting into two:  Problem type	Pricing, Help me understand when I will be charged
    Problem type   Pricing
    Problem subtype   Help me understand when I will be charged
 3. Update screenshot as attached.
![support2](https://user-images.githubusercontent.com/11367710/76643800-cc0ebc80-6523-11ea-956f-0b5b6318a3c5.jpg)

**Comment by polichtm** [comment]
updated instructions - there is no screenshot in the current version of the walkthrough
