### ISSUE TITLE
AZ-900 Labs

### ISSUE THREAD

**Issue by garymitchell** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#37]
# Module: 00
#### Step: 00

Thank you for your virtual classroom on 3/3 and 3/4.  Walkthroughs are a lot of fun to try out and they upgrade my Azure skills dramatically.  There is one incorrect walkthrough; that is, Walkthrough 06: Implement an Azure IoT Hub causes an error message to say that SKU:B1 Basic Tier disallows the creation of a new device.  I switched from B1 to S1 in SKU field and completed the walkthrough.  Could you update the walkthrough so that others will have easier time to finish it?

**Comment by itbland** [comment]
This works as written; perhaps it was a little slow provisioning when you tried it?
Glad that you enjoyed the class and the labs!
-Eric, MCT

**Comment by polichtm** [comment]
Hi Gary 
updated
rgds
Marcin
