### ISSUE TITLE
Screen capture changes

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#46]
I have screen capture changes for this course. I can edit the text, but I can't upload files:

> Uploads are disabled.
> File uploads require push access to this repository.

How should these edits be made?

Mike Smith

**Comment by polichtm** [comment]
Hi Mike
are you creating a pull request?
rgds
Marcin

**Comment by microsmith** [comment]
> are you creating a pull request?



Yes. I’ve updated other MOC labs and DOCS articles. This is the first time I’ve needed to update an image referenced by the updated page.

 

What steps do I need to follow?

 

Thanks,

 

Mike Smith

MCT, MVP Office Apps & Services (SharePoint)

Senior Instructor

MAX Technical Training  
Phone: 513.322-8888 | 866-595-6863 |  <https://mail.maxtrain.com/owa/UrlBlockedError.aspx> www.maxtrain.com
blog: TechTrainingNotes.blogspot.com <http://techtrainingnotes.blogspot.com/> 

@TechTrainNotes

**Comment by polichtm** [comment]
Hi Mike,
Pls follow https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
rgds
Marcin

**Comment by microsmith** [comment]
Marcin,

 

Thanks for the quick follow up. I guess I need to learn more about Github. I can’t initiate a pull request (button is not active), but I can edit the text and propose a file change. (I have made numerous text edits to other MOC and DOCS articles.) The edit that I need to make is requires an image to link to, and I cannot upload that without a pull request.

 

For now, I’ll create my own copy of the labs for my students with the updated steps and screen captures. One day I will revisit how to make the updates in Github.

 

Mike Smith

**Comment by polichtm** [comment]
Hi Mike,
Pls paste the images into your response and provide lab, exercise, task, and step number to which they are applicable
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response

**Comment by microsmith** [comment]
I'm delivering this course again in a few weeks. I'll collection the images during that class and submit them. Just ran out of time this time around.
