### ISSUE TITLE
07-Implement Azure OUTDATED!

### ISSUE THREAD

**Issue by falodunos** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#50]
# Module: 02 - Core Azure Services
##Title: 07 - Implement Azure Functions
#### Step: 00

Description of issue
Screenshots and part of the instruction is out of date and inconsistent with with Azure current UI.

Kindly provide update to avoid frustration!

Thank you

**Comment by polichtm** [comment]
updated
rgds
Marcin
