### ISSUE TITLE
18 - Explore the Trust Center

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#53]
Can we please update the name of this walk-through to be more inclusive? It actually covers 3 distinct services.

**Comment by polichtm** [comment]
Hi Vitaly,
what name would you suggest?
rgds
Marcin

**Comment by VitalyMCT** [comment]
How about "Explore Trust Center, Service Trust Portal and Compliance Manager"?

**Comment by staleycyn** [comment]
Changing the name of the Lab affects the student materials in Skillpipe. I can put this on the change list for the next version, but changing it now will cause confusion.

**Comment by R-C-Stewart** [comment]
This lab is being removed in the next version of the course, in favor of a different scenario; so we will continue to follow's the previous comment and hold off on the change until the next release.
