### ISSUE TITLE
Screenshot update required

### ISSUE THREAD

**Issue by GhumanNavneet** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#57]
# Module: 03
#### Step: 05

Description of issue

Screenshot need to update for selecting policy definition as Require specific tag to Require a tag on resource. Please find the new screenshot below:

![image](https://user-images.githubusercontent.com/33318387/86245499-3036b880-bbc7-11ea-8fce-bc4aa9a5a50a.png)

**Comment by GhumanNavneet** [comment]
Any update?

**Comment by Randall-Knapp** [comment]
This has been updated with the new screenshot above.
