### ISSUE TITLE
Lab 4 - Monitoring insights are out of preview

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#60]
> On the storage account blade, scroll down to the Monitoring section and click Insights (preview).

statement should be updated to review "(preview)". Likewise for the corresponding screenshot.

**Comment by R-C-Stewart** [comment]
Updated the graphic and text to show that Monitoring Insights is no longer in Preview.  Thanks for the fix request and apologies for the delay in updating.
