### ISSUE TITLE
Module 0 Certification areas 

### ISSUE THREAD

**Issue by Tyr03** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#61]
# Module: 00
#### Step: 00

Description of issue

In the PowerPoint slideshow for the module 00 the slide 9 needs to be updated with the latest Certification areas 

Study areas | Weights
-- | --
Describe   cloud concepts | 15-20%
Describe   core Azure services | 30-35%
Describe security,  privacy, compliance, and trust | 25-30%
Describe   Azure pricing Service Level Agreements, and Lifecycles | 25-30%

Same error in the Trainer's Handbook, page 3

**Comment by R-C-Stewart** [comment]
I updated the powerpoints, they should release within the next 10 days.  Thanks for catching this one!!
