### ISSUE TITLE
Module 02 - Core Azure Services	09 - Create a VM with a Template

### ISSUE THREAD

**Issue by Ouza70** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#64]
# Module: 02
#### Step: 08

There is no Check the box I agree to the terms and conditions stated above and then click Purchase.

Repro steps:

1. Skip step 08, click review + create.
2. Results in Validation failed. View error details message.
3. Error details are: {"message":"The template deployment 'Microsoft.Template-20200901131951' is not valid according to the validation procedure. The tracking id is '9360535b-1714-4f6a-8416-8af875a81d21'. See inner errors for details."}
4. Abort this lab at task 01 due to failure.

**Comment by R-C-Stewart** [comment]
You were correct... I tested the lab and the CHECK BOX has been removed.  I have refreshed the lab to remove this step and validated the the Template published correctly per the other steps.
