### ISSUE TITLE
Sequence of Labs

### ISSUE THREAD

**Issue by Uwe3169** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#86]
Hello,

in my opinion, the sequence of the labs is not right, it doesn´t match the workflow of the course. Is it possible to change it like here: https://github.com/NHTrainer/AZ-900T01/tree/master/Instructions/Walkthroughs ?

In Lab 20 - Use the Azure TCO Calculator, we build 2 Server to host 50 VM each. I just wonder, how 50 VM should work with just 8 cores and 16GB RAM on the host? This is absolutely NOT realistic - in no way. Maybe it is possible to adjust that? I know, it is just to show the functionality, i just guess it should be more realistic.

**Comment by Randall-Knapp** [comment]
Hello,

Thanks for the feedback. I do have a few questions.

First, I'm not sure who NHTrainer is and I am not familiar with the repo that was created. Are you NHTrainer? The repo that is being updated and that does have the up to date order is the repo that you put this issue on. I have no ownership or visibility into the link posted above (https://github.com/NHTrainer/AZ-900T01/tree/master/Instructions/Walkthroughs). The appropriate corresponding link to the link you posted above is https://github.com/MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals/tree/master/Instructions/Walkthroughs. It should have the correct content.

Second, can you provide more clarity on what you are looking for with Lab 20 https://github.com/MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals/blob/master/Instructions/Walkthroughs/20-Use%20the%20Azure%20TCO%20Calculator.md?  What is it specifically that you feel would be more realistic?

Thank you!

**Comment by Uwe3169** [comment]
Hello again,

yes, I am Trainer @ NewHorizons in Germany and just did the Videos and Labs for the Training. I followed the Microsoft Official Course Document and by that, the right sequence of labs should be:
00-Readme-Error Log.md
01-Create a virtual machine.md
02-Deploy Azure Container Instances.md
03-Create a virtual network.md
04-Create Blob storage.md
05-Create a SQL database.md
06-Implement the Azure IoT Hub.md
07-Implement Azure Functions.md
08-Create a Web App.md 
09-Create a VM with a Template.md
10-Create a VM with PowerShell.md
11-Create a VM with the CLI.md
12-Secure network traffic.md
13-Implement Azure Key Vault.md
14-Create an Azure Policy.md
15-Manage access with RBAC.md
16-Manage resource locks.md
17-Implement resource tagging.md
18-Explore the Trust Center.md
19-Use the Azure Pricing Calculator.md
20-Use the Azure TCO Calculator.md
21-Open a Support Request.md
22-Calculate Composite SLAs.md
23-Access Azure Preview features.md

To the second point. Let´s guess, we need the Host for 50 VMs running Windows 10 32bit. Therefore the minimum requirements are 1 Processor, 1GB of RAM. It is possible to use 1 physical core for 4 virtual Processors so we need at least 12 cores and 64GB RAM on the host - with this, it would be able to START the 50 VMs, but it would be absolutely no fun to work with them. Just to give you an idea about how much performance would be a little bit more realistic :-)

**Comment by Uwe3169** [comment]
i just recognized, that microsoft changed the course outline on december 4th. by that, your sequence is right. it doesn´t makes any sence to change the outline that way, but anyway ^^
