### ISSUE TITLE
Warning Should be Added, I lost permission for Subscriptions mistakenly  remove role

### ISSUE THREAD

**Issue by gyzi** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#89]
# Module: 14-Manage access with RBAC
#### Step: 00

Description of issue:
**Warning Should be Added, I lock my Subscriptions mistakenly following these steps and remove my role assignment for Subscriptions **

Repro steps:

1. From Subscriptions IAM 
2. role assignment,  " #Task2: remove role " from filter it can be remove without been notified wanring

**I open request support for this but this really important to be noted from someone doing walkthrough  directly from this lab guide**

**Comment by Randall-Knapp** [comment]
@gyzi Can you give more details on where you think the warning should be?
